export const ADD_ALERT_MESSAGE = 'ADD_ALERT_MESSAGE';
export const DELETE_ALERT_MESSAGE = 'DELETE_ALERT_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_INFO_RECEIVED = 'USER_INFO_RECEIVED';
